@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 19 12:26:34 +0000 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim d_ff_reset_TB_behav -key {Behavioral:sim_1:Functional:d_ff_reset_TB} -tclbatch d_ff_reset_TB.tcl -view C:/Users/ruair/Documents/Vivado/LabF_A/d_ff_reset_TB_behav_posedge.wcfg -log simulate.log"
call xsim  d_ff_reset_TB_behav -key {Behavioral:sim_1:Functional:d_ff_reset_TB} -tclbatch d_ff_reset_TB.tcl -view C:/Users/ruair/Documents/Vivado/LabF_A/d_ff_reset_TB_behav_posedge.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
